#ifndef _CONSTANTES_
#define _CONSTANTES_

enum estados_personaje{
	PARADO,
	PARADO_DERECHA,
	PARADO_ARRIBA,
	ANDAR_DERECHA,
	PARADO_ABAJO,
	PARADO_IZQUIERDA,
	ANDAR_IZQUIERDA,
	ANDAR_ARRIBA,
	ANDAR_ABAJO,   
	MAX_ESTADOS
};

const Uint32 WIDTH=640;
const Uint32 HEIGHT=480;
const Uint32 TWIDTH=32;
const Uint32 THEIGHT=32;

#endif
